# Generated by Django 5.0.7 on 2024-07-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_downloadablefile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadableFile',
        ),
    ]
